V2 666 create app and rootlayout
For-Hives/my-makeup pull request #693
Opened 2024-08-28 15:42 UTC by Fansoa

2024-08-28 20:01 UTC, CinquinAndy requested changes

2024-08-28 20:01 UTC, CinquinAndy commented on app/layout.js
> +
on devrait mettre une description "par défaut" et un "title" etc, par défaut dans le layout Root. 
genre un truc du genre
export const metadata = {
	description: 'My-Makeup...',
	title: 'My-Makeup...',
}

à voir ce qui est le plus cohérent en terme de SEO , peut être prendre ce qui est marqué dans la landing de base de my makeup (en prod) , il me semble que c'était pas mal

2024-08-29 13:01 UTC, Fansoa commented on providers/SessionProviderWrapper/index.js
done

2024-08-29 13:10 UTC, Fansoa commented on app/layout.js
> +
Pour la description j'ai opté pour la description déjà présente page d'accueil du site.

Done

2024-08-29 13:34 UTC, CinquinAndy approved these changes

2024-08-29 13:35 UTC, merged