(feat) Profil page
For-Hives/my-makeup pull request #73
Opened 2023-04-27 19:57 UTC by CinquinAndy

2023-05-14 21:06 UTC, LightInn requested changes
Je dois t'avouer que j'ai fait des commentaire qui servent a rien au milleux et que je m'en suis rendu compte apres <3

2023-05-14 21:06 UTC, LightInn commented on src/components/Profil/Atoms/ModalUpdate/ModalUpdateSkillsProfil.js
> +	const [open, setOpen] = useState(props.modalUpdateSkillsProfil)
```suggestion
	const [isModalOpen, setIsModalOpen]  = useState(props.modalUpdateSkillsProfil)
```

2023-05-14 21:06 UTC, LightInn commented on src/components/Profil/Atoms/ModalUpdate/ModalUpdateSocialMediaProfil.js
> +	const [open, setOpen] = useState(props.modalUpdateSocialMediaProfil)
```suggestion
	const [isModalOpen, setIsModalOpen]  = useState(props.modalUpdateSocialMediaProfil)
```

2023-05-14 21:06 UTC, LightInn commented on src/components/Profil/Atoms/ModalUpdate/ModalUpdatePortfolioProfil.js
> +	const [open, setOpen] = useState(props.modalUpdatePortfolioProfil)
```suggestion
	const [isModalOpen, setIsModalOpen] = useState(props.modalUpdatePortfolioProfil)
```

2023-05-14 21:06 UTC, LightInn commented on src/components/Profil/Atoms/ModalUpdate/ModalUpdateResumeProfil.js
> +	const [open, setOpen] = useState(props.modalUpdateResumeProfil)
```suggestion
	const [isModalOpen, setIsModalOpen] = useState(props.modalUpdateResumeProfil)
```

2023-05-14 21:12 UTC, CinquinAndy commented on src/styles/icons.css
> +/*	font-variation-settings: 'FILL' 0, 'wght' 400, 'GRAD' 0, 'opsz' 48;*/
done

2023-05-14 21:12 UTC, CinquinAndy commented on src/styles/loader.css
> +        transform: translateX(-31px);
ça se passe bien partout tkt bb

2023-05-14 21:12 UTC, CinquinAndy commented on src/styles/loader.css
> +        transform: translateX(-31px);
( en vrai on verra dans la partie responsive plus tard, mais dans la théorie c'est bon )

2023-05-14 21:19 UTC, CinquinAndy commented on next.config.js
> +				hostname: '**.andy-cinquin.fr',
il passe pas par my-makeup mais par le s3 qui est sur andy-cinquin.fr

2023-05-14 21:19 UTC, CinquinAndy commented on package.json
> +		"material-icons": " 1.13.6",
bien vu bb

2023-05-14 21:22 UTC, CinquinAndy commented on src/components/Global/Footer.js
> +						<Link href="/" rel={'noopener nofollow noreferrer'}>
https://github.com/For-Hives/my-makeup/issues/43#issuecomment-1547004230

2023-05-14 21:22 UTC, CinquinAndy commented on src/components/Global/ResponsiveTemporary.js
> +function ResponsiveTemporary(props) {
🤔💰💰

2023-05-14 21:29 UTC, CinquinAndy commented on public/assets/brand/2673627-social-media-logos/font/flaticon.html
tkt j'ai push quelques modifs pour régler ça

2023-05-14 21:30 UTC, CinquinAndy commented on src/components/Profil/Childs/SocialMediaProfil.js
> +								alt={`${user?.user?.first_name} ${user?.user?.last_name} website`}
j'ai compris ce que tu voulais dire

2023-05-14 21:38 UTC, CinquinAndy commented on src/pages/_document.js
> +				{/*<link*/}
done

2023-05-14 21:40 UTC, CinquinAndy commented on src/pages/a-propos.js
> +					<ResponsiveTemporary />
flemme de faire un truc chiant à faire pour pas le répéter alors que c'est jetable
-

2023-05-14 21:40 UTC, CinquinAndy commented on src/pages/site-map.js
> +					<ResponsiveTemporary />
certe

2023-05-14 21:44 UTC, CinquinAndy commented on src/services/utils.js
> +	return classes.filter(Boolean).join(' ')
à pas grand chose en vrai,c'est la méthode qu'ils utilisent pour concaténer les classes sur tailwind ui ,j'homogénéise ça

2023-05-14 21:50 UTC, CinquinAndy commented on src/services/PatchMeMakeup.js
> +			console.log(err)
oui

2023-05-14 21:51 UTC, CinquinAndy commented on src/services/PatchMeMakeup.js
> +			console.log(err)
il faudrait

2023-05-14 21:52 UTC, CinquinAndy commented on src/services/PatchMeMakeup.js
> +			console.log(err)
#93

2023-05-14 21:52 UTC, CinquinAndy commented on src/services/PutMakeupArtisteViaId.js
> +				last_name: data.last_name,
oui

2023-05-14 21:53 UTC, CinquinAndy commented on src/services/PutMakeupArtisteViaId.js
> +				last_name: data.last_name,
c'est delete, c'était provisoire en attendant que tu fasse la partie patch

2023-05-14 21:53 UTC, CinquinAndy commented on src/pages/profil.js
> +				`${process.env.NEXT_PUBLIC_API_URL}api/me-makeup`,
j'ai jamais réussi à l'externalisé et le faire fonctionner correctement

2023-05-14 21:54 UTC, CinquinAndy commented on src/pages/profil.js
> +				`${process.env.NEXT_PUBLIC_API_URL}api/me-makeup`,
faut que je me penche dessus calmement mais sur un autre ticket je pense

2023-05-14 21:55 UTC, CinquinAndy commented on src/pages/profil.js
> +				`${process.env.NEXT_PUBLIC_API_URL}api/me-makeup`,
#94

2023-05-14 21:55 UTC, CinquinAndy commented on src/pages/profil.js
> +	if (status !== 'authenticated') {
effectivement, j'avais dis que je le ferais

2023-05-14 21:56 UTC, CinquinAndy commented on src/pages/profil.js
> +	if (status !== 'authenticated') {
#95

2023-05-14 21:57 UTC, CinquinAndy commented on src/components/Profil/Atoms/ToggleButton.js
> +				className={classNames(
c'est mieux là tkt 
![image](https://github.com/For-Hives/my-makeup/assets/55706543/0d113e7b-36b9-4d98-92e7-021e134ea05b)

2023-05-14 21:58 UTC, CinquinAndy commented on src/components/Profil/Atoms/ModalUpdate/ModalUpdateCoursesProfil.js
> +const schema = yup.object().shape({
mdrr, merci pour ça

2023-05-14 21:59 UTC, CinquinAndy commented on src/components/Profil/Atoms/ModalUpdate/ModalUpdateCoursesProfil.js
> +const schema = yup.object().shape({
#96

2023-05-14 21:59 UTC, CinquinAndy commented on src/components/Profil/Childs/SkillsProfil.js
> +	const { view } = router.query
à première view tu veux dire ? :3

2023-05-14 22:05 UTC, CinquinAndy commented on src/components/Profil/Childs/SkillsProfil.js
> +	const mode = !!view
done

2023-05-14 22:18 UTC, CinquinAndy commented on src/components/Profil/Childs/SkillsProfil.js
> +	const [modalUpdateSkillsProfil, setModalUpdateSkillsProfil] =
done

2023-05-14 22:18 UTC, CinquinAndy commented on src/components/Profil/Parents/InfosProfil.js
> +	const mode = !!view
done

2023-05-14 22:18 UTC, CinquinAndy commented on src/components/Profil/Parents/InfosProfil.js
> +							<span className="material-icons-round text-indigo-900">edit</span>
done

2023-05-14 22:19 UTC, CinquinAndy commented on src/components/Profil/Parents/InfosProfil.js
> +								visibility
c'est l'icone de material bb

2023-05-14 22:19 UTC, CinquinAndy commented on src/components/Profil/Childs/ServiceOffers/ServiceOffersProfil.js
> +	const [modalUpdateServiceOffersProfil, setModalUpdateServiceOffersProfil] =
done

2023-05-14 22:20 UTC, CinquinAndy commented on src/components/Profil/Childs/ServiceOffers/ServiceOffersProfil.js
> +							<span className="material-icons-round">edit</span>
done

2023-05-14 22:20 UTC, CinquinAndy commented on src/components/Profil/Childs/CoursesProfil.js
> +	const [modalUpdateCoursesProfil, setModalUpdateCoursesProfil] =
done

2023-05-14 22:20 UTC, CinquinAndy commented on src/components/Profil/Childs/ExperiencesProfil.js
> +		React.useState(false)
done

2023-05-14 22:20 UTC, CinquinAndy commented on src/components/Profil/Childs/ExperiencesProfil.js
> +							<span className="material-icons-round">edit</span>
done

2023-05-14 22:20 UTC, CinquinAndy commented on src/components/Profil/Childs/DescriptionProfil.js
> +		React.useState(false)
done

2023-05-14 22:20 UTC, CinquinAndy commented on src/components/Profil/Childs/LanguageProfil.js
> +		React.useState(false)
done

2023-05-14 22:20 UTC, CinquinAndy commented on src/components/Profil/Childs/LocationProfil.js
> +		React.useState(false)
done

2023-05-14 22:21 UTC, CinquinAndy commented on src/components/Profil/Childs/LocationProfil.js
> +							{props.user?.city} & {props.user?.action_radius}km autour
je suis pas d'accord

2023-05-14 22:22 UTC, CinquinAndy commented on src/components/Profil/Childs/PortfolioProfil.js
> +		React.useState(false)
done

2023-05-14 22:24 UTC, CinquinAndy commented on src/components/Profil/Childs/PortfolioProfil.js
> +							console.log(swiper.activeIndex)
done

2023-05-14 22:24 UTC, CinquinAndy commented on src/components/Profil/Childs/PortfolioProfil.js
> +							console.log(ev)
done

2023-05-14 22:24 UTC, CinquinAndy commented on src/components/Profil/Childs/PortfolioProfil.js
> +								console.log(mySwiper.slides.length - 1)
done

2023-05-14 22:24 UTC, CinquinAndy commented on src/components/Profil/Childs/PortfolioProfil.js
> +							<span className={'font-semibold text-indigo-950'}>Suivant</span>
done

2023-05-14 22:25 UTC, CinquinAndy commented on src/components/Profil/Parents/ResumeProfil.js
> +	const mode = !!view
done

2023-05-14 22:25 UTC, CinquinAndy commented on src/components/Profil/Parents/ResumeProfil.js
> +		React.useState(false)
done

2023-05-14 22:25 UTC, CinquinAndy commented on src/components/Profil/Parents/ResumeProfil.js
> +	const [starsToDisplay, setStarsToDisplay] = React.useState(5)
ui

2023-05-14 22:26 UTC, CinquinAndy commented on src/components/Profil/Parents/ResumeProfil.js
> +	const [starsToDisplay, setStarsToDisplay] = React.useState(5)
#97

2023-05-14 22:26 UTC, CinquinAndy commented on src/components/Profil/Atoms/ModalUpdate/ModalUpdateCoursesProfil.js
> +	const [open, setOpen] = useState(props.modalUpdateCoursesProfil)
done

2023-05-14 22:26 UTC, CinquinAndy commented on src/components/Profil/Atoms/ModalUpdate/ModalUpdateDescriptionProfil.js
> +	const [open, setOpen] = useState(props.modalUpdateDescriptionProfil)
done

2023-05-14 22:26 UTC, CinquinAndy commented on src/components/Profil/Atoms/ModalUpdate/ModalUpdateExperiencesProfil.js
> +	const [open, setOpen] = useState(props.modalUpdateExperiencesProfil)
done

2023-05-14 22:27 UTC, CinquinAndy commented on src/components/Profil/Atoms/ModalUpdate/ModalUpdateLanguageProfil.js
> +	const [open, setOpen] = useState(props.modalUpdateLanguageProfil)
done

2023-05-14 22:27 UTC, CinquinAndy commented on src/components/Profil/Atoms/ModalUpdate/ModalUpdateLocationProfil.js
> +	const [open, setOpen] = useState(props.modalUpdateLocationProfil)
done

2023-05-14 22:27 UTC, CinquinAndy commented on src/components/Profil/Atoms/ModalUpdate/ModalUpdateServiceOffersProfil.js
> +	const [open, setOpen] = useState(props.modalUpdateServiceOffersProfil)
done

2023-05-14 22:27 UTC, CinquinAndy commented on src/components/Profil/Atoms/ModalUpdate/ModalUpdateSkillsProfil.js
> +	const [open, setOpen] = useState(props.modalUpdateSkillsProfil)
done

2023-05-14 22:27 UTC, CinquinAndy commented on src/components/Profil/Atoms/ModalUpdate/ModalUpdateSocialMediaProfil.js
> +	const [open, setOpen] = useState(props.modalUpdateSocialMediaProfil)
done

2023-05-14 22:27 UTC, CinquinAndy commented on src/components/Profil/Atoms/ModalUpdate/ModalUpdatePortfolioProfil.js
> +	const [open, setOpen] = useState(props.modalUpdatePortfolioProfil)
done

2023-05-14 22:27 UTC, CinquinAndy commented on src/components/Profil/Atoms/ModalUpdate/ModalUpdateResumeProfil.js
> +	const [open, setOpen] = useState(props.modalUpdateResumeProfil)
done

2023-05-15 08:16 UTC, LightInn reviewed
zut de flute

2023-05-15 08:16 UTC, LightInn commented on src/components/Profil/Atoms/ModalUpdate/ModalUpdateCoursesProfil.js
> +export default function IsModalOpen(props) {
Heu.... tu a fait une betise bebou... :/ 
Tu a remplacer le nom de toute fonctions :fearful:

2023-05-15 08:21 UTC, CinquinAndy commented on src/components/Profil/Atoms/ModalUpdate/ModalUpdateCoursesProfil.js
> +export default function IsModalOpen(props) {
ah oupsi doupsi

2023-05-15 08:33 UTC, CinquinAndy commented on src/components/Profil/Atoms/ModalUpdate/ModalUpdateCoursesProfil.js
> +export default function IsModalOpen(props) {
fixed

2023-05-15 08:51 UTC, LightInn commented on src/components/Profil/Atoms/ModalUpdate/ModalUpdateCoursesProfil.js
> +export default function IsModalOpen(props) {
Tu a pas modif la documentation en commantaire au dessus, du coup la elle sert a rien

2023-05-15 08:56 UTC, CinquinAndy commented on src/components/Profil/Atoms/ModalUpdate/ModalUpdateCoursesProfil.js
> +export default function IsModalOpen(props) {
quels commentaires ?

2023-05-15 09:21 UTC, LightInn approved these changes
allé vas gamin !

2023-05-15 14:43 UTC, merged