feat(#23): system de recherche des maquilleuses
For-Hives/my-makeup pull request #75
Opened 2023-04-28 00:06 UTC by LightInn

2023-04-29 15:04 UTC, CinquinAndy approved these changes

2023-04-29 15:04 UTC, CinquinAndy commented on src/styles/globals.css
> +	transition: all 0.2s;
faut pas faire ça, les navigateurs aimes pas du tout

2023-04-29 15:04 UTC, CinquinAndy commented on src/styles/loader/escalator.css
> +#loader {
trop cool l'animation

2023-04-29 15:05 UTC, CinquinAndy requested changes
fix fuzzy

2023-04-30 13:59 UTC, LightInn commented on src/styles/loader/escalator.css
> +#loader {
Oui tu a vue !

2023-04-30 19:41 UTC, CinquinAndy approved these changes

2023-04-30 21:37 UTC, merged